# frozen_string_literal: true

require_relative "factory/duck"
require_relative "factory/frog"
require_relative "factory/habitat"
require_relative "factory/duck_pond"
require_relative "factory/frog_pond"
require_relative "factory/algae"
require_relative "factory/frog_algae_pond"
require_relative "factory/water_lily"
require_relative "factory/duck_water_lily_pond"
require_relative "factory/tree"
require_relative "factory/tiger"
require_relative "factory/pond_organism_factory"
require_relative "factory/jungle_organism_factory"
require_relative "factory/organism_factory"
